cache-dir = ".ruff_cache"
line-length = 100
indent-width = 4
target-version = "py313"
include = ["project/**/*.py"]

[lint]
select = ["ALL"]
ignore = ["D100", "D103", "D101", "D102", "D104", "D107", "TRY400"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
